### PR TITLE
[JENKINS-54929] Always flush the output logger on the TaskListener

### PR DESCRIPTION
**Pull request by stevendpclark**
- Extract the logger out of the TaskListener and pass it to the stdout/stderr methods of the Launcher
 - Trap all errors and force a flush of the logger once the command has completed

### CODE REVIEW

**Comment by dhoer** [comment]
👍

**Comment by moochael** [comment]
@jcsirot This PR was created for [JENKINS-54929](https://issues.jenkins-ci.org/browse/JENKINS-54929).

Can I please trouble you to review this?

**Comment by okynos** [comment]
Hello Jenkins team,

We have problems with Ansible output too, there is an ETA on such PR to be merged?, thanks.

Regards.

**Comment by MSAskew** [comment]
It's a royal shame to see this just sitting here. The bug is infuriating on a daily basis for me currently.
Build failed due to not being able to delete a folder.

**Comment by christianharke** [comment]
*bump* - ...to any contributor of this repository: how can I help to get this bug fix merged?

**Comment by MSAskew** [comment]
No clue on the rules around this, but a colleague compiled the changes above as we wanted it in the office. I've uploaded the jar here: https://github.com/MSAskew/compiled-ansible-plugin-fix

Copied the jar into the right location on the Jenkins box and it appears to be functioning correctly. Three deployments have failed today and all of them showed me the trace to the end.

Just incase anyone else wants to make use of the fix, thank you @stevendpclark for making it!

**Comment by jonesbusy** [comment]
Hi,

I'm now maintainer of this plugin. I would like to test it and release a new version in the next fews days.

Best regards,

**Comment by jonesbusy** [comment]
I needed to rebase on master.

Superseded by https://github.com/jenkinsci/ansible-plugin/pull/40

**Comment by AFurryCat** [comment]
Pleased to see this finally sorted out! Thanks @jonesbusy :)

**Pull request closed without merging**
