### PR TITLE
Added vaultTmpPath option (#133)

### PR DESCRIPTION
**Pull request by bbobbettoS**
Added vaultTmpPath option to set a different temporary path, rather than the default workspace,for temporary files generated by interacting with the vault

Fixes https://github.com/jenkinsci/ansible-plugin/issues/133

### Testing done
I have created a new pipeline for testing, added a new test case in pipeline section and in my own jenkins instance after updating the plugin and added vaultTmpPath: '/var/jenkins_home/secrets/' I have verified that the file vault***.password was created and deleted in that path

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by jonesbusy** [comment]
Hi,

Thanks for your contribution

Test are failings on CI : https://ci.jenkins.io/job/Plugins/job/ansible-plugin/view/change-requests/job/PR-134/1/console

```
java.io.IOException: Failed to create a temp file on \tmp
```

Can you update test to write a writable location ?

Thanks

**Comment by bbobbettoS** [comment]
I setted up a Windows environment and my tests are ok, in this case the error is a 'timeout', I don't know why

**Comment by jonesbusy** [comment]
I've rested the build. Looks it was some issue with Windows infrastructure.

Will take a look at the PR in the following days.

**Comment by jonesbusy** [comment]
While the code looks good I'm just wonder about security.

I know providing any path to --vault-password-file is a ansible feature.

But here we will copy a Jenkins Secret outside the workspace that can be temporary read by other process. Even if the secret is removed

I'm just trying to avoid an this plugin get and other security advisory.

Regards,

**Comment by bbobbettoS** [comment]
Yeah, but actually the default behavior in my case is a major security flaw, because the password file is saved in workspace that I share with other people, that can read it while the pipeline is running. With this option I can save the password file in /var/jenkins_home/secrets/ and conceil it from them

**Review by jonesbusy — APPROVED** [review]

**Comment by jonesbusy** [comment]
Hi,

Thanks for your patience. I will merge this PR soon. I want to perform a release of the Ansible plugin before to separate the changes (And probably wait until the 2.414.3 release is out).

Regards,

**Pull request merged**
