### PR TITLE
Use latest parent project definition

### PR DESCRIPTION
**Pull request by alecharp**
This will fix the `<disctributionManagement/>` issue with the release

### CODE REVIEW

**Comment by alecharp** [comment]
Well as I'm a CloudBees employee, I still have to get internal approval: please @reviewbybees, this is a really easy one.

**Comment by alecharp** [comment]
It is possible that findbugs still complain but 

```
if (computer == null || computer.getNode() == null) {
  throw new AbortException("..");
}
```

does make sure that `computer.getNode()` is not null when calling `perform` method.

**Comment by jcsirot** [comment]
I've pushed the modifications and now the build passes (https://jenkins.ci.cloudbees.com/job/plugins/job/ansible-plugin/78/console)
Can I merge the PR or should I wait for the review from another bee?

**Comment by alecharp** [comment]
@jcsirot where did you make the changes? They don't appear in this PR..

**Comment by jcsirot** [comment]
I pushed in your branch (https://github.com/jenkinsci/ansible-plugin/tree/alecharp-master, commit e08232f3cb54da930f5e2a3fab54f4ec099146fb). I used to think that the PR would have been automatically updated but it seems that it did not.

**Comment by alecharp** [comment]
@jcsirot you pushed to this repository, not mine. Otherwise, the PR would have been updated ;)

**Comment by alecharp** [comment]
There is a bug here because even if I `git pull -r alecharp master` I cannot see your commit

**Comment by jcsirot** [comment]
I've created a new branch with the changes. You should be able to see it https://github.com/jenkinsci/ansible-plugin/tree/findbugs-fix-false-positive

**Pull request merged**
