### PR TITLE
Move docs to GitHub

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Move docs to GitHub

Hacktoberfest submission to move documentation from Jenkins Wiki to GitHub.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes

Thanks to Docs Office Hours for the help @dheerajodha, @kwhetstone , @stackscribe

Supersedes #33 

@jcsirot are you still available to maintain this plugin or should it be listed as "up for adoption"?

### CODE REVIEW

**Comment by nstankov-bg** [comment]
Looks great, thanks for doing this!

**Comment by MarkEWaite** [comment]
@escoem this documentation pull request is ready for review.  I've collected the documentation from wiki.jenkins.io and placed it into the README.

**Comment by MarkEWaite** [comment]
> Looks this plugin need maintenance and a good refresh (bom, etc...) Current release still rely on 1.609.1 Jenkins.
> 
> Ping @escoem @jcsirot

Thanks, though I don't think that pinging the inactive maintainers will change the state of the plugin.  It needs to be adopted by others.

If you're a user of the plugin, it would be a great thing if you could adopt the plugin, merge this pull request, and update the plugin dependencies and development environment.

**Comment by jonesbusy** [comment]
Thanks,

Yes user of this plugin. Will probably ask co-maintenance. I don't want to dig into this plugin internals nor fix/implement new feature but only keeping in a good state.

Waiting few days to see if receiving an answer from maintainers.

Regards,

**Comment by MarkEWaite** [comment]
> Will probably ask co-maintenance

That's what I've done in several cases and it has helped users without being too much of a burden for me.

It is also OK if someone adopts a plugin, makes a small set of improvements, and then decides that they don't want to continue as a maintainer of that plugin.  They've made those improvements and others benefit from those improvements, whether or not the new maintainer is able to continue.

**Comment by jonesbusy** [comment]
Draft PR for the refresh : https://github.com/jenkinsci/ansible-plugin/pull/38

**Pull request merged**
