### PR TITLE
[JENKINS-42445] Support hostKeyChecking = true in pipeline dsl	

### PR DESCRIPTION
**Pull request by escoem**
hostKeyChecking can be also configured when using pipeline

### CODE REVIEW

**Comment by escoem** [comment]
hi @jcsirot, do you need anything else regarding the PR?

**Comment by escoem** [comment]
hi @jcsirot, do you need anything else regarding the PR?

**Comment by escoem** [comment]
@reviewbybees

**Comment by daniel-beck** [comment]
Why is this disabled by default? Security should be opt-out. What am I missing?

**Comment by dwnusbaum** [comment]
I agree with @daniel-beck that security should be opt-out, especially since this is a new setting. 

The existing places where this setting is available ([AnsiblePlaybookBuilder](https://github.com/jenkinsci/ansible-plugin/blob/f930ff827a2e9bc6d287fcb3339c867a86630cdb/src/main/resources/org/jenkinsci/plugins/ansible/AnsiblePlaybookBuilder/config.jelly#L54-56) and [AnsibleAdHocCommandBuilder](https://github.com/jenkinsci/ansible-plugin/blob/f930ff827a2e9bc6d287fcb3339c867a86630cdb/src/main/resources/org/jenkinsci/plugins/ansible/AnsibleAdHocCommandBuilder/config.jelly#L46-48)) default to false in the UI, so it might be a good idea to switch those defaults as well.

**Comment by daniel-beck** [comment]
TBH I think these should also be changed to `true` (in a separate PR), unless I'm missing something about Ansible that makes this not a big deal.

@jcsirot Are you still maintaining this plugin? WDYT?

**Comment by escoem** [comment]
@daniel-beck @dwnusbaum  I have kept the same default behaviour. I agree, in another PR we can suggest true by default. I can help with the plugin management if @jcsirot agree

**Comment by dwnusbaum** [comment]
@escoem I think that it is a good idea to go ahead and make the default `true` here since it's a newly accessible setting, and to create a PR to change the defaults for the existing places where host key checking is configured.

**Comment by daniel-beck** [comment]
@dwnusbaum Do not disagree, but needs maintainer support, as it's a breaking change for existing pipelines due to https://github.com/jenkinsci/ansible-plugin/pull/14/files#diff-c5a2189abaf681466c8a8cddd68d4d13L323

**Comment by dwnusbaum** [comment]
@daniel-beck Good point, I was mistaken in thinking it wouldn't affect existing pipelines.

**Pull request merged**
