### PR TITLE
Add support for Boolean extra-var interpretation

### LINKED ISSUE #100: Boolean extra variables being interpreted as Strings
### Jenkins and plugins versions report
<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.413
OS: Linux - 5.15.0-76-generic
Java: 11.0.19 - Ubuntu (OpenJDK 64-Bit Server VM)
---
ansible:240.vc26740a_625c0
  ```

</details>

The only way Ansible can detect boolean extra-variables is by passing JSON using the `extras` parameter, like shown below.  
Otherwise, they are interpreted as **Strings**.
```groovy
ansiblePlaybook(
    playbook: './src/main.yml',
    extras: '''
        --extra-vars "{bar: false}"
    '''
)
```
Equivalent when using the terminal:
```sh
$ ansible-playbook playbook.yml --extra-vars "{bar: false}"
```

### What Operating System are you using (both controller, and any agents involved in the problem)?

Alpine Docker container running Ansible.

### Reproduction steps

1. Declare a variable in Ansible that should default to a different value if extra variable is given as `false`:
```yaml
foo: "{{ bar | default(99, true) }}"
```
2. Run the script through Jenkins:
```groovy
ansiblePlaybook(
    playbook: './src/main.yml',
    extraVars: [
        'bar': false
    ]
)
```

### Expected Results

```
foo: 99
```

### Actual Results

```
foo: "false"
```

### PR DESCRIPTION
**Pull request by Pexers**
## Add support for Boolean extra-var interpretation

Checks if extra variables are Boolean and, if so, applies a JSON format.

Closes #100

### References
- [Defining variables at runtime](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#defining-variables-at-runtime)

### Testing done

1. Confirmed that automated tests (`mvn test`) pass on Linux with Java 21.
2. Tested a small use-case.
    1. Declared some Ansible script variables that show a message if value of extra variable is given as `false`:
      ```sh
      apple: "{{ apple_bool | default('Apple not found!', true) }}"
      lemon: "{{ lemon_bool | default('Lemon not found!', true) }}"
      mango: "{{ mango_str  | default('Mango not found!', true) }}"
      ````
    2. Run the script through Jenkins.
      ```sh
      ansiblePlaybook(
          playbook: './src/main.yml',
          extraVars: [
              'apple_bool': true,
              'lemon_bool': false,
              'mango_str': "true"
          ]
      )
      ```
    3. Verified that the result was shown as expected through a script.
      ```sh
      - name: Include variables
        include_vars: "main.yml"
      
      - name: "Apple exists?"
        debug:
          var: apple
      
      - name: "Lemon exists?"
        debug:
          var: lemon
      
      - name: "Mango exists?"
        debug:
          var: mango
      ```
      ```sh
      TASK [debug : Apple exists?] ***************************************************
      ok: [localhost] => {
          "apple": true
      }
      
      TASK [debug : Lemon exists?] ***************************************************
      ok: [localhost] => {
          "lemon": "Lemon not found!"
      }
      
      TASK [debug : Mango exists?] ***************************************************
      ok: [localhost] => {
          "mango": true
      }
      ```

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by jonesbusy** [comment]
Hi,

Thanks for your PR, looks good to me.

But the CI is failing: https://ci.jenkins.io/job/Plugins/job/ansible-plugin/job/PR-225/2/console

```
08:41:02  [ERROR] Run 'mvn spotless:apply' to fix these violations.
```

Thanks

**Review by jonesbusy — CHANGES_REQUESTED** [review]
Fix build

**Review by jonesbusy — APPROVED** [review]

**Comment by zhengyongtao** [comment]
This change is too destructive, directly converting true and false to Boolean values, which will cause the variable judgments passed to the script to be collectively invalidated. For example, I need to pass false to the shell script, but now it becomes False. This is a disaster for builds!

**Comment by zhengyongtao** [comment]
I think we should distinguish between true and "true" rather than converting them both to Boolean values.

**Pull request merged**
